### ISSUE TITLE
RFE: allow additional headers in Slurm batch scripts besides "#SBATCH"

### ISSUE THREAD

**Issue by bcfriesen** [eth-cscs/reframe#29] opened 2018-01-04 17:09 UTC
The "Cori" system at NERSC has a burst buffer which interfaces with Slurm via the `#DW` batch script headers. Consequently, jobs which use the burst buffer have a mix of `#SBATCH` and `#DW` headers, e.g.,

```
#!/bin/bash

#SBATCH -p regular
#SBATCH -N 1
#SBATCH -C haswell
#SBATCH -t 01:00:00
#DW jobdw capacity=10GB access_mode=striped type=scratch
#DW stage_in source=/global/cscratch1/sd/username/path/to/filename destination=$DW_JOB_STRIPED/filename type=file
#DW stage_out source=$DW_JOB_STRIPED/dirname destination=/global/cscratch1/sd/username/path/to/dirname type=directory

srun ./hello.ex
```

Other examples of burst buffer scripts of varying complexity are provided [here](http://www.nersc.gov/users/computational-systems/cori/burst-buffer/example-batch-scripts/).

Would it be possible to allow a mix of such headers in the batch scripts that ReFrame generates?

**Comment by vkarak** [comment] 2018-01-04 17:36
Hi @bcfriesen, first of all, thanks for trying ReFrame! We are also experimenting with burst buffers and DataWarp, but such features are not yet in production in our systems, thus ReFrame does not support them. In principle, adding support for these Slurm directives is not difficult. A thing to consider, however, is how these would be exposed through the `RegressionTest` API. What would you like to see there? I will also go through the link you provided to better understand your test case.

**Comment by bcfriesen** [comment] 2018-01-04 18:15
Hi @vkarak,

> A thing to consider, however, is how these would be exposed through the RegressionTest API. What would you like to see there?

The design choice for DataWarp integration with Slurm is unusual in my opinion. In fact I was mistaken in the original issue, there are in fact *two* different Slurm batch headers for interacting with DataWarp: `#DW` and `#BB` (the latter used exclusively for creating and destroying persistent reservations on DW).

Since these seem to be hard-coded into Slurm now, maybe one way to do it is to enhance the `extra_resources` field, e.g., for using DW as scratch,
```
        self.extra_resources = {
          'datawarp' : [
            'jobdw' : 'jobdw capacity=10GB access_mode=striped type=scratch'
            'stage_in' : 'source=/global/cscratch1/sd/username/path/to/filename destination=$DW_JOB_STRIPED/filename type=file'
            'stage_out' : 'source=$DW_JOB_STRIPED/dirname destination=/global/cscratch1/sd/username/path/to/dirname type=directory'
          ]
        }
```
(Pardon the likely-incorrect Python, I'm a novice.) For creating a PR,
```
        self.extra_resources = {
          'datawarp' : [
            'create_persistent' : 'name=myBBname capacity=100GB access_mode=striped type=scratch'
          ]
        }
```
For destroying a PR,
```
        self.extra_resources = {
          'datawarp' : [
            'destroy_persistent' : 'name=myBBname capacity=100GB access_mode=striped type=scratch'
          ]
        }
```
And for using an existing PR,
```
        self.extra_resources = {
          'datawarp' : [
            'persistentdw' : 'name=myBBname'
          ]
        }
```
and then telling ReFrame explicitly behind the scenes that `jobdw`, `stage_in`, `stage_out`, and `persistentdw` need the `#DW` header, while `create_persistent`, and `destroy_persistent`need the `#BB` header. Pretty sure those are the only 6 headers that DataWarp/Slurm understand.

**Comment by vkarak** [comment] 2018-01-05 14:06
The `extra_resources` is just a simple dictionary that you specify values for the additional resources that you define in your configuration file. Have a look [here](https://eth-cscs.github.io/reframe/reference.html#reframe.core.pipeline.RegressionTest.extra_resources). However, the idea you're proposing could be rewritten like this:

```python 
# in your config file
'resources': {
    'jobdw': ['#DW jobdw {jobdw}'],
    'stage_in': ['#DW stage_in {stage_in}'],
    'stage_out': ['#DW stage_out {stage_out}']
    'create_persistent': ['#BB {create_persistent}']
    ...
}

# in your test file
self.extra_resources = {
    'jobdw': 'capacity=10GB access_mode=striped type=scratch',
    'stage_in': 'source=/global/cscratch1/sd/username/path/to/filename destination=$DW_JOB_STRIPED/filename type=file',
    'stage_out': 'source=$DW_JOB_STRIPED/dirname destination=/global/cscratch1/sd/username/path/to/dirname type=directory',
    'create_persistent': '...'
}
```

This, however, won't work out of the box right now (although the syntax is correct for ReFrame), because it will always prefix the generated preamble lines with `#SBATCH`. Perhaps, we could add a feature in ReFrame to substitute `#SBATCH` with another prefix if specified in resources.

**Comment by vkarak** [comment] 2018-01-11 14:21
Hi @bcfriesen,

We have implemented the feature you requested and it should be available with the next release of ReFrame. More specifically, you may now define your `resources` in the configuration file as follows (just an example):

```python
'resources': {
    'datawarp': [
        '#DW jobdw capacity={capacity} access_mode={mode} type=scratch'
        '#DW stage_out source={out_src} destination={out_dst} type={stage_filetype}'
    ]
}
```

And in your regression test file you may then request them as follows:

```python
self.extra_resources = {
    'datawarp': {
        'capacity': '100GB',
        'mode': 'striped',
        'out_src': '$DW_JOB_STRIPED/name',
        'out_dst': '/my/file',
        'stage_filetype': 'file'
    }
}
```

Alternatively, you may also define the resources as follows:

```python
'resources': {
    'datawarp_jobdw': ['#DW jobdw capacity={capacity} access_mode={mode} type=scratch'],
    'datawarp_stageout': ['#DW stage_out source={src} destination={dst} type={type}']
}
```

In this case, your `extra_resources` will look like the following:

```python
self.extra_resources = {
    'datawarp_jobdw': {'capacity': '100GB', 'mode': 'striped'},
    'datawarp_stageout': {'src': '$DW_JOB_STRIPED/name', 'dst': '/my/file', 'type': 'file'}
}
```

How does it look?

**Comment by bcfriesen** [comment] 2018-01-11 17:11
Looks great! Thanks for implementing this so quickly, @vkarak. Looking forward to testing it out.

**Comment by vkarak** [comment] 2018-01-24 14:50
Hi @bcfriesen,

ReFrame 2.9 is freshly released! Let us know if the new syntax for extra resources is sufficient for your usage.

You can check also the documentation of the configuration [here](https://eth-cscs.github.io/reframe/configure.html#partition-configuration) and the `extra_resources` [here](https://eth-cscs.github.io/reframe/reference.html#reframe.core.pipeline.RegressionTest.extra_resources).

**Comment by bcfriesen** [comment] 2018-01-24 17:03
Great! Thanks @vkarak. I will test this and report back.

**Comment by vkarak** [comment] 2018-02-09 09:36
Hi @bcfriesen, did you finally try this feature?

**Comment by bcfriesen** [comment] 2018-02-09 23:08
Hi @vkarak, apologies for the delay. It does work, but I think there is a minor typo in the example provided in the documentation which prevents it from working if copied verbatim. On this page (https://eth-cscs.github.io/reframe/configure.html), this part
```
'resources': {
    'datawarp': [
        '#DW jobdw capacity={capacity} access_mode={mode} type=scratch'
        '#DW stage_out source={out_src} destination={out_dst} type={stage_filetype}'
    ]
}
```
should have a comma at the end of the first `#DW` line. Otherwise both lines are ignored altogether and the generated Slurm script will have neither. Do you agree?

**Comment by vkarak** [comment] 2018-02-10 19:02
Good catch! It's indeed a typo. We'll fix it in the upcoming release. Without the comma, I would expect to emit everything in a single line, not to ignore it completely. I'll double check that, too.

**Comment by bcfriesen** [comment] 2018-02-13 00:38
Actually it was a combination of a typo in the documentation, and a typo in my own code. Adding the comma in the docs and fixing my own bug made the case work correctly.

**Comment by bcfriesen** [comment] 2018-02-13 22:03
Actually, now there is a new issue related to this.

When using DataWarp, the scheduler creates a new temporary directory on the DataWarp file system which is pointed to by an environment variable. For "striped" access, the environment variable is `$DW_JOB_STRIPED`. The data specified by the `#DW stage_in` header in the batch script is automatically copied to `$DW_JOB_STRIPED`. The remainder of the batch script typically involves copying the executable into `$DW_JOB_STRIPED`, because the value of that environment variable changes with every run (so it can't be hard-coded into the batch script, or into the code itself).

I tried to address this by writing a simple bash script which copies the executable into `$DW_JOB_STRIPED`:
```
#!/bin/bash
EXE=a.out
cp $EXE $DW_JOB_STRIPED
cd $DW_JOB_STRIPED
```
 and putting it into the `self.job.pre_run` stage as described [here](https://eth-cscs.github.io/reframe/advanced.html). The issue is that the auto-generated Slurm script will execute that bash script, but then follow it immediately with `cd /path/to/stagedir`, as specified by the `stagedir` in the `_site_configuration`. So the test never actually tests the functionality of DataWarp because it reads everything from `stagedir`, which is not on the DataWarp file system.

**Comment by vkarak** [comment] 2018-02-14 09:26
Yes, that's a bug of our Slurm script generator. I will open a new issue on that and close this one. The `cd` to the working directory should be done at the very beginning or we should try using the `--workdir` option of Slurm instead.

There is though a workaround you can try by using a [`LauncherWrapper`](https://eth-cscs.github.io/reframe/reference.html#reframe.core.launchers.LauncherWrapper) to emit the `cd $DW_JOB_STRIPED &&` just before the `srun` command:

```python
from reframe.core.launchers import LauncherWrapper

def setup(self, partition, environ, **job_opts):
    super().setup(partition, environ, **job_opts)
    self.job.launcher = LauncherWrapper(self.job.launcher, 'cd $DW_JOB_STRIPED && ')
```

**Comment by vkarak** [comment] 2018-02-14 09:46
Opened issue #35 to follow up on this.

**Closed by vkarak** 2018-02-14 09:46 UTC
Labels: enhancement, framework, prio: normal
