### ISSUE TITLE
Abstract reframe tests

### ISSUE THREAD

**Issue by jjotero** [eth-cscs/reframe#1555] opened 2020-10-26 17:25 UTC
### Intro
In its current version, the base definition of a reframe test is typically in the same file or directory as its derived tests. From there on, test specialisation is done through a mix of class inheritance and if statements. This implies that tests are rather difficult to share across different users, who might be using a completely different system, programming environment, compiler options, etc.

The proposed feature of **_abstract reframe tests_**, enables abstracting away individual reframe tests in simple python modules, where test specialisation occurs by using the given python modules and extending the desired reframe test through simple class inheritance. Similarly to C++ abstract classes, abstract reframe tests have members that are not implemented (e.g. the list of valid partitions, list of valid programming environments, modules, etc) and these _abstract members_ are implemented by a child class. Therefore, the use of abstract tests would allow the reframe community to contribute their tests into a shared test library, where every single test in this library is not specialised to any particular system or programming environment.

### A Hello World Example
Because these abstract cases might not be complete (i.e. they might have abstract members), the tests cannot be registered by reframe by using the decorators `@rfm.simple_test` and  `@rfm.parameterized_test`. Instead, the new proposed decorators `@rfm.simple_abstract_test` and `@rfm.parameterized_abstract_test` are used to flag a class as an abstract test. The `@rfm.simple_abstract_test` decorator simply enables the child tests to keep track of the directory where the abstract class was defined. This means that these child tests will be able to retrieve the source of the abstract test correctly (see example below). For more complex cases, the decorator `@rfm.parameterized_abstract_test` enables setting default test parameters that can be later overridden by any child test. Also, for a more advanced use, multiple abstract tests can be _chained_ together, enabling a complex combination of test parameters. To illustrate all this, we show a simple hello world example, where the source
``` c++
#include <iostream>
  
#ifndef EXTRA
# define EXTRA "base"
#endif
int main()
{
  std::cout << "Hello, World! (" <<  EXTRA << ")" << std::endl;
  return 0;
}
```
takes a preprocessor flag `EXTRA` that extends the most basic `Hello, World!` output. This file is located under the directory where the reframe abstract tests are defined; for example, in `$RFM_DIR/abstractTestLibrary/hello/src/hello.cpp`. Thus, the abstract reframe tests would live in `$RFM_DIR/abstractTestLibrary/hello/hello.py`.
```python
import reframe as rfm
import reframe.utility.sanity as sn

# Log the abstract test and do not register the test.
@rfm.simple_abstract_test
class HelloAbstract(rfm.RegressionTest):
    def __init__(self):
        self.valid_systems = ['*']
        self.valid_prog_environs = ['*']
        self.sourcepath = 'hello.cpp'
        self.sanity_patterns = sn.assert_found(r'Hello, World\!', self.stdout)


# Log the abstract test and do not register the test.
# Note that we're extending a simple_abstract_test to a parametrized_abstract_test!
@rfm.parameterized_abstract_test(['a'], ['b'], ['c'])
class HelloParameterizedAbstract(HelloAbstract):
    def __init__(self, flags):
        super().__init__()
        self.build_system = 'SingleSource'
        self.executable = 'a.out'
        self.build_system.cxxflags = [r'-DEXTRA="\"%s\""' % flags]
        self.sanity_patterns = sn.assert_found(r'Hello, World\!', self.stdout)
```
Note how these tests are completely system agnostic. In fact, due to their simplicity, these classes are not even abstract classes and are complete and ready to run as reframe tests. However, these tests could be made fully abstract by removing `self.valid_systems` and `self.valid_prog_environs` from the `HelloAbstract` class. In this example, the class `HelloAbstract` is a simple abstract case, and the class `HelloParameterizedAbstract` is a parametrised abstract case with default parameters `['a'], ['b'], ['c']`. These default parameters can be later overridden, extended, filtered, etc. but we'll get to that later.  

#### Simple abstract test
So, we now have our abstract test library, but how do we use that? Easy, we simply inherit the abstract test from our python module containing the abstract tests and wrap it with `@rfm.simple_test`.

```python
import reframe as rfm
import reframe.utility.sanity as sn

# Import the python module with the abstract tests.
import abstractTests.hello.hello_abstract_tests as tt 


@rfm.simple_test
class HelloTest(tt.HelloAbstract):
    '''
    Inherit the simple_template and register it as a test.
    This test will use identical settings to those defined in the template.

    Logically, the class tt.HelloAbstract is the HelloAbstract class defined in
    the code snippet above.
    '''

    def __init__(self):
        super().__init__()

        # If the class tt.HelloAbstract would not have (for example) the test 
        # parameters self.valid_systems or self.valid_prog_environs, they 
        # would have to be defined in here.
```
Therefore, we now just have to simply point reframe to this file in order to run the `HelloTest` check. Note how the `cpp` source code is not in the same directory as this `HelloTest` class, but because the class `tt.HelloAbstract` was decorated as a simple abstract test, reframe is able to retrieve the sources from the right directory.

#### Parametrised abstract test
Now let's have a look into the more advanced features using `@rfm.parameterized_abstract_test`. Remember how the parametrised abstract test in our abstract test library had some default parameters defined? To use those default parameters we just need:
```python
import reframe as rfm
import reframe.utility.sanity as sn
import abstractTests.hello.hello_abstract_tests as tt

@rfm.simple_test
class HelloDefaultParameters(tt.HelloParameterizedAbstract):
    '''
    Inherit from a parametrized abstract test and run the case with the
    parameters defined in the abstract test definition. Note that __init__
    must have the same arguments than the class it inherits from. This is
    because the simple_test decorator takes care of feeding this class the
    default test arguments defined on the parametrized abstract test
    tt.HelloParameterizedAbstract class.
    ''' 
        
    def __init__(self, flags):
        super().__init__(flags)
```
It cannot get easier than this. The decorator `@rfm.simple_test` is aware that the inherited class is a parametrised abstract test, and it does take care of feeding this child class the right test parameters. Sure, but what if you don't want those default parameters? Then you simply override them :)
```python
# Same imports here as in the snippet above.

@rfm.parameterized_test(['d'])
class HelloOverrideParameters(tt.HelloParameterizedAbstract):
    def __init__(self, flags):
        super().__init__(flags)
```
Here, `@rfm.parameterized_test` is aware that the class `tt.HelloParameterizedAbstract` is in fact an parametrised abstract test, and it overrides the default parameters `['a'], ['b'], ['c']` and replaces them by `['d']`. So what if we now want to combine all the parameters?
```python
@rfm.parameterized_test(['d'], inherit_params=True)
class HelloExtendParameters(tt.HelloParameterizedAbstract):
    '''
    Now we extend the default parameter list.
    '''

    def __init__(self, flags):
        super().__init__(flags)
```
The decorator argument `inherit_params` controls whether the test parameters are overridden or not. Now, what if we just want some of the existing parameters and not all of them?
```python
@rfm.parameterized_test(inherit_params=True, filt_params=lambda x: x[1:])
class HelloFilterParameters(tt.HelloParameterizedAbstract):
    '''
    Here we just filter out some of the default test parameters.
    '''

    def __init__(self, flags):
        super().__init__(flags)
```
The argument `filt_params` takes a function that modifies the argument tuple. In this example, we simply pop the first of the test parameters `['a']`. Of course, we can also extend the parameters AND filter some of the existing ones out:
```python
@rfm.parameterized_test(['d'], inherit_params=True, filt_params=lambda x: x[1:])
class HelloFilterExtendParameters(tt.HelloParameterizedAbstract):
    ''' 
    Now we filter some of the default test parameters out and also extend the
    list with new parameters.
    '''

    def __init__(self, flags):
        super().__init__(flags)
```
And lastly, to make even more complex combinations of the test parameters, `fuse_params` takes any user defined function to combine the existing test parameters with the new ones. For example, here we transform the argument list from `['a'], ['b'], ['c']` to `['ad'], ['bd'], ['cd']`:
```python
def expand(x, y):
    '''This function could be made more elegant with itertools, but it's just here illustrate the point.'''
    temp = []
    for i in x:
        for j in y:
            temp.append([i[0]+j[0]])
    return tuple(temp)


@rfm.parameterized_test(['d'], inherit_params=True, fuse_params=expand)
class HelloFuseParameters(tt.HelloParameterizedAbstract):
    '''
    Lastly, we introduce some custom combination of the existing test
    parameters and the new ones.
    '''

    def __init__(self, flags):
        super().__init__(flags)
```

As a last side note, it is also worth mentioning that an abstract test can be created by inheriting from other abstract tests. This allows the user to potentially use the filtering and fusing methods over multiple steps to write complex test argument lists in a very compact way. Creating an abstract test by inheriting from another abstract test will not override the base source directory as long as the decorator's argument `set_base_path` is NOT set to `True` (defaults to `False`).
```python
@rfm.parameterized_abstract_test(['d'], inherit_params=True)
class HelloAbstractExtendedParameters(tt.HelloParameterizedAbstract):
    '''
    This does NOT register the test - it is still an abstract test.
    Here we just create an abstract test from another abstract test.
    '''

    def __init__(self, flags):
        super().__init__(flags)
# and


@rfm.simple_test
class HelloExtendParameters2(HelloAbstractExtendedParameters):
    '''
    But this DOES registers the tests - no longer an abstract test.
    '''

    def __init__(self, flags):
        super().__init__(flags)
```

### Implementation
The bulk of the implementation to the above functionality takes place in `reframe/core/decorators.py`, where the abstract test decorators look as follows
```python

def simple_abstract_test(cls, set_base_path=False):
    '''
    Class decorator for injecting the _rfm_abs_test_prefix class attribute.
    This attribute is used on the reframe pipeline to set the default dirs
    of the check.

    The decorated class must derive from
    :class:`reframe.core.pipeline.RegressionTest`.  This decorator is also
    available directly under the :mod:`reframe` module.

    :arg set_base_path: Flag to control the base test path override. If
         an abstract test inherits from another abstract test, the base
         test path will remain as the base abstract case's one, unless
         set_base_path is se to True.

    .. note::
    This function does not register the reframe test.
    '''
    if not hasattr(cls, '_rfm_abs_test_prefix') or set_base_path:
        cls._rfm_abs_test_prefix = os.path.abspath(
            os.path.dirname(inspect.getfile(cls)))
    return cls


def _set_filt_params(arg):
    return (lambda x: x) if (arg is None) else arg


def _set_fuse_params(arg):
    return (lambda x, y: x+y) if (arg is None) else arg


def parameterized_abstract_test(*inst, inherit_params=False, filt_params=None,
                                fuse_params=None, set_base_path=False):
    '''
    Class decorator extends the simple_abstract_test decorator and injects
    the _rfm_abs_test_params class attribute. This attribute holds the args to
    be used at a later stage during the registration of the checks as 
    parametrized tests (*inst). See below parameterized_test for a full 
    description of the arguments.

    The decorated class must derive from
    :class:`reframe.core.pipeline.RegressionTest`.  This decorator is also
    available directly under the :mod:`reframe` module.

    .. note::
    This function does not register the reframe test.
    '''

    _filt_params = _set_filt_params(filt_params)
    _fuse_params = _set_fuse_params(fuse_params)

    def _do_not_register(cls):
        cls._rfm_abs_test_params = inst if (
            not hasattr(cls, '_rfm_abs_test_params') or
            not inherit_params) else _fuse_params(
            _filt_params(cls._rfm_abs_test_params), inst)
        return simple_abstract_test(cls, set_base_path)

    return _do_not_register
```
Also, in order to extend the existing `@rfm.simple_test` and `@rfm.parameterized_test` to deal with these abstract tests as described above, these decorators have to be modified as
```python
def simple_test(cls):
    '''Class decorator for registering parameterless tests with ReFrame.

    The decorated class must derive from
    :class:`reframe.core.pipeline.RegressionTest`.  This decorator is also
    available directly under the :mod:`reframe` module.

    If the decorated class inherits from a parametrized abstract test, this
    function will register all the default parametrized tests defined on the
    parent abstract test class.

    .. versionadded:: 2.13
    '''

    _validate_test(cls)
    if hasattr(cls, '_rfm_abs_test_params'):
        for args in cls._rfm_abs_test_params:
            _register_test(cls, args)

    else:
        _register_test(cls)

    return cls


def parameterized_test(*inst, inherit_params=False,
                       filt_params=None, fuse_params=None):
    '''Class decorator for registering multiple instantiations of a test class.

    The decorated class must derive from
    :class:`reframe.core.pipeline.RegressionTest`. This decorator is also
    available directly under the :mod:`reframe` module.

    :arg inst: The different instantiations of the test. Each instantiation
         argument may be either a sequence or a mapping.
    :arg inherit_params: If False, the test will discard any potential default
         parameters inferited from a parameterized_abstract_test. Contrarily, if
         set to True, *inst will add to the parameters under cls._rfm_abs_test_params.
    :arg filt_params: Filtering function to eliminate/expand/manipulate the existing
         test parameters inherited from a parameterized_abstract_test. It only has an
         effect if the argument inherit_params is True. By default, it leaves the
         existing test parameters unaltered.
    :arg fuse_params: Combinatorial function that allows for any complex merging
         operation of the two sets of test parameters cls._rfm_abs_test_params and inst.
         By default, it simply joins both sets.

    .. versionadded:: 2.13

    .. note::
       This decorator does not instantiate any test.  It only registers them.
       The actual instantiation happens during the loading phase of the test.
    '''

    _filt_params = _set_filt_params(filt_params)
    _fuse_params = _set_fuse_params(fuse_params)

    def _do_register(cls):
        _validate_test(cls)
        abs_test_args = _filt_params(cls._rfm_abs_test_params) if (hasattr(
            cls, '_rfm_abs_test_params') and inherit_params) else ()
        for args in _fuse_params(inst, abs_test_args):
            _register_test(cls, args)

        return cls

    return _do_register
```

**Comment by vkarak** [comment] 2020-10-26 20:29
Couldn't we simply have non-decorated class as abstract test classes? We could possibly get the right prefix through some metaclass magic.

**Comment by vkarak** [comment] 2020-10-26 21:27
What if the tests looked like that somehow:

```python
import reframe as rfm
import reframe.core.fields as fields
import reframe.utility.sanity as sn
import reframe.utility.typecheck as typ


class StreamTest(rfm.RegressionTest, abstract=True):
    template_param('cores', int)
    template_param('flags', typ.List[str])
    perf_param('Copy', 'MB/s')
    perf_param('Scale', 'MB/s')
    perf_param('Add', 'MB/s')
    perf_param('Triad', 'MB/s')

    def __init__(self):
        self.prebuild_cmds = [
            'wget http://www.cs.virginia.edu/stream/FTP/Code/stream.c',
        ]
        self.build_system = 'SingleSource'
        self.sourcepath = 'stream.c'
        self.build_system.cppflags = ['-DSTREAM_ARRAY_SIZE=$((1 << 25))']
        self.sanity_patterns = sn.assert_found(r'Solution Validates',
                                               self.stdout)
        self.perf_patterns = {
            'Copy': sn.extractsingle(r'Copy:\s+(\S+)\s+.*',
                                     self.stdout, 1, float),
            'Scale': sn.extractsingle(r'Scale:\s+(\S+)\s+.*',
                                      self.stdout, 1, float),
            'Add': sn.extractsingle(r'Add:\s+(\S+)\s+.*',
                                    self.stdout, 1, float),
            'Triad': sn.extractsingle(r'Triad:\s+(\S+)\s+.*',
                                      self.stdout, 1, float)
        }

    @rfm.run_before('compile')
    def setflags(self):
        environ = self.current_environ.name
        self.build_system.cflags = self.flags

    @rfm.run_before('run')
    def set_num_threads(self):
        self.num_cpus_per_task = self.cores
        self.variables = {
            'OMP_NUM_THREADS': str(self.cores),
            'OMP_PLACES': 'cores'
        }


class SpecializedStreamTest(StreamTest):
    @rfm.run_after('setup')
    def prepare_test(self):
        self.set_param('cores',  4, when=curr_sys('catalina:default'))
        self.set_param('cores', 12, when=curr_sys('daint:gpu'))
        self.set_param('cores', 36, when=curr_sys('daint:mc'))
        self.set_param('cores', 10, when=curr_sys('daint:login'))

        self.set_param(
            'flags', ['-fopenmp', '-O3', '-Wall'], when=curr_env('cray')
        )
        self.set_param(
            'flags', ['-fopenmp', '-O3', '-Wall'], when=curr_env('gnu')
        )
        self.set_param(
            'flags', ['-qopenmp', '-O3', '-Wall'], when=curr_env('intel')
        )
        self.set_param('flags', ['-mp', '-O3'], when=curr_env('pgi'))

        self.add_reference('Copy',  25200, -0.05, 0.05,
                           when=curr_sys('catalina'))
        self.add_reference('Scale', 25200, -0.05, 0.05,
                           when=curr_sys('catalina'))
        self.add_reference('Add',   25200, -0.05, 0.05,
                           when=curr_sys('catalina'))
        self.add_reference('Triad', 25200, -0.05, 0.05,
                           when=curr_sys('catalina'))
```

@jjotero This idea builds on top of yours. First, since we are already using metaclasses, I think we can avoid the decorator and use arguments for the special abstract classes, but that remains to be seen in detail. Then we can defined typed template parameters with the `template_param()`. That can be simply a shortcut to the `cores = fields.TypedField('core', int)` in this example. The default base tests can come with predefined template parameters, such as the `modules`, `variables` etc. We could possibly distinguish between required and not required parameters. For example, `modules` and `variables` may be optional and get a default value as of now. Basically, all the fields that we have now can be test parameters than can be optionally set.

The actual tests would only have to set the `valid_systems` and `valid_prog_environs` and any required parameters, in this example, `cores` and `flags` and if a performance test, they can also add reference values. For the `set_param()` and `add_reference()` methods, I'm using the syntax we're introducing now with dependencies using the `when` callable. The idea is that the `when` argument is a callable that accepts a `System`, `SystemPartition` and `Environment` combination; it will be called by the framework with `self.current_system`, `self.current_partition` and `self.current_environ`. 

There are still some things to address or pay attention to:

1. I haven't addressed inheritance in abstract tests, which I think it should straightforward.
2. One tricky part is when any pipeline hooks defined in the abstract test class will run. We want them to run last, but with the current implementation will run first, if I'm not mistaken.
3. I haven't addressed parameterized abstract tests, but again we could for them with a metaclass parameter list.

What do you think?

**Comment by jjotero** [comment] 2020-10-27 12:27
@vkarak I think there're two different things here that should not be mixed together. One is how to define the abstract tests and the second is how to do the setting and checking for those abstract parameters. On this second point (which is what you show on the snippet above) I do agree with you and that's something it was not addressed on the initial comment. As for how to best declare a test as abstract, I'm not sure if going through the metaclass is the most transparent solution. The way I see abstract tests is as just regular tests, but just deferring their registration. Given that this is such a similar procedure to registering the normal reframe tests, I don't see why one would do these two very similar things differently.  Also, IMO, the most powerful thing about the abstract decorators is how you can write very complicated parametrised test in a very compact way, and I'm not sure how this would be possible without the decorators.

**Comment by vkarak** [comment] 2020-10-27 14:42
> The way I see abstract tests is as just regular tests, but just deferring their registration.

An un-decorated test is unregistered and you can still inherit from it. So I'm missing the real value of the decorator. If it is for setting the sourcepath correctly, I believe we can do that without a decorator. Similarly with parameterized templated tests. I'm totally in favor of the idea of facilitating the creation of test libraries. My example, goes mostly into extending the current interface to support this better and make it also easier for users to grasp.

Regarding the discussion between metaclasses vs. class decorators, they're practically the same except that metaclasses give you much more control and since we already use them for the test creation, why not using them more. From the user's point of view, I don't know if it's gonna be a big difference, because they won't have to fiddle with the metaclass itself.

Here is a PoC of the `template_param()` implementation (I call it `test_param()` to be more neutral, but I again I don't know if it's the best name):

```python
import functools
import reframe.core.fields as fields


def _test_param(namespace, param, param_type):
    namespace[param] = fields.TypedField(param, param_type)
    print('setting template param on class')


class Meta(type):
    @classmethod
    def __prepare__(cls, name, bases, **kwargs):
        namespace = super().__prepare__(cls, name, bases, **kwargs)
        namespace['test_param'] = functools.partial(_test_param, namespace)
        return namespace


class C(metaclass=Meta):
    test_param('cores', int)

    def __init__(self):
        print('object init')


if __name__ == '__main__':
    c = C()
    c.cores = 10
#    c.cores = 'foo'
```

If you uncomment the last statement, it will fail with a `TypeError` as expected.

**Comment by vkarak** [comment] 2020-10-27 14:44
In the above example, see `C` as `RegressionTest`. All subclasses, i.e., will use the same metaclass, so users will never have to pass `metaclass`. That's the advantage of metaclasses against decorators, whereas for decorators we will have to decorate each class. Metaclasses allow a more uniform implementation of the built-in `RegressionTest` and user-specific library tests.

**Comment by vkarak** [comment] 2020-10-27 22:44
I have created a [gist](https://gist.github.com/vkarak/be9e88fa3c86abd50bfaac04a97d5fa5) trying to rewrite the current Gromacs test in the CSCS repository using a variation of the syntax described above. I have split the test into the "library" part, i.e., the non site-specific, as well as the CSCS-specific parameterization. Most of the new elements proposed are syntactic sugar that will allow us to write tests in a more concise way. The current syntax is not broken and will be still in effect and totally valid.

**Comment by jjotero** [comment] 2020-11-02 14:15
Right, I think we should break things up a little bit more. How about introducing the concept of **base tests**?  In this context, and similarly to c++, a base test would be a non-specialised test (not necessarily an abstract test) that lives in a library and might have the test sources with it. This would mean that tests that inherit from this base test will need to retrieve the sources (if any) from the base test's directory. This would replace the functionality introduced by the `simple_abstract_test` decorator shown above, which now that I think about it, the name was kinda wrong. To get this done, we just modify the metaclass slightly in order to insert the `cls._rfm_base_test_prefix attribute`. This would be then picked up by the reframe pipeline and that's job done. See example below.

```python
import os, inspect

class TestMeta(type):
    def __new__(cls, name, bases, namespace, **kwargs):
        return super().__new__(cls, name, bases, namespace)

    def __init__(cls, name, bases, namespace, base_test=None, **kwargs):
        super().__init__(name, bases, namespace, **kwargs)
        if base_test:
            cls._rfm_base_test_prefix = os.path.abspath(
                os.path.dirname(inspect.getfile(cls)))


class BaseTest(metaclass=TestMeta, base_test=True):
    '''
    Test where the sources are. It sets the cls._rfm_base_test_prefix attribute.
    This goes in the test library and may or may not be an abstract test.
    '''
    def __init__(self):
        pass

    
class DerivedTest(BaseTest):
    '''
    This derived test could be in a different file from BaseTest. 
    Because this derived test inherits from BaseTest, reframe will
    retrieve the right sources (located in the same dir as BaseTest)
    using the cls._rfm_base_test_prefix attribute.
    '''
    pass
    

if __name__ == '__main__':
    foo = DerivedTest()
    try:
      print(foo._rfm_base_test_prefix)
    except:
      pass
```

Perhaps this can make for a nice and simple PR on its own?

I'll share what I've got on the parameterized abstract tests later :)

**Comment by jjotero** [comment] 2020-11-02 16:54
Here is the prototype implementation for the abstract parametrised tests.

```python
import copy

class InstrumentedParameter:
    '''
    Test parameter (name + values) and other attributes to deal with the
    test parameter inheritance/chaining.

    TODO: Type checking.
    '''
    def __init__(self, name, values=None, inherit_params=False, filt_params=None):
        '''
        name: parameter name
        values: parameter values
        inherit_params: If false, it overrides all previous values set for the parameter.
        filt_params: Function to filter/modify the inherited values for the parameter.
             It only has an effect if used with inherit_params=True.
        '''
        # If the values are None (or an empty list), the parameter is considered as
        # declared but not defined (i.e. an abstract parameter).
        if values is None:
            values = []

        # The values arg must be a list.
        if not isinstance(values, list):
            raise ValueError(f'Parameter values must be defined in a list.') from None

        # Default filter is no filter.
        if filt_params is None:
            filt_params = lambda x: x

        self.name = name
        self.values = values
        self.inherit_params = inherit_params
        self.filt_params = filt_params

    def is_undef(self):
        '''
        Handy function to check if the parameter is undefined (empty).
        '''
        if self.values == []:
            return True

        return False


class ParameterPack:
    '''
    Bundle containing the test parameters inserted in each test (class).
    This is a callable class, where the __call__ method is the interface
    used to add new parameters to the reframe test.
    '''
    def __init__(self):
        self.parameter_list = []

    def __call__(self, name, defaults=None, inherit_params=False, filt_params=None):
        self.parameter_list.append(InstrumentedParameter(name, defaults, inherit_params, filt_params))


class ReframeAttributes:
    '''
    Storage class hosting all the custom reframe class attributes.
    '''
    def __init__(self):
        self._rfm_parameters = ParameterPack()
        # Other attributes to follow in here ...

class TestMeta(type):
    '''
    The regression test metaclass
    '''

    @classmethod
    def __prepare__(cls, name, bases, **kwargs):
        namespace = super().__prepare__(name, bases, **kwargs)

        # Create an instace of the ReframeAttributes class to populate
        # the class namespace with the custom reframe attributes.
        # The idea is to host all the attributes in this class (whose instance
        # is private), and to make it's members accessible as function pointers.
        namespace['__rfm_attributes'] = ReframeAttributes()

        # Make the attribute to add test parameters accessible in the class namespace
        # as rfm_parameter. Test parameters can be added as:
        # `rfm_parameter('P0', int, [0,1,2,3])`.
        namespace['rfm_parameter'] = namespace['__rfm_attributes']._rfm_parameters

        # More attributes to come ...

        return namespace

    def __new__(cls, name, bases, namespace, **kwargs):
        return super().__new__(cls, name, bases, namespace, **kwargs)

    def __init__(cls, name, bases, namespace, **kwargs):
        super().__init__(name, bases, namespace, **kwargs)

        # Build the parameter space for the current class in a temp dict
        staging_params = {}

        # Import the parameter spaces from the base classes
        for b in bases:
            try:
                base_params = copy.deepcopy(b._rfm_params)
                for key in base_params:

                    # With multiple inheritance, a single parameter could be doubly defined
                    # and lead to repeated values.
                    # TODO: add type checking here too.
                    if key in staging_params:
                        if not (staging_params[key].is_undef() or base_params[key].is_undef()):
                            raise KeyError(f'Parameter space conflict (on {key}) '
                                           f'due to multiple inheritance.') from None

                    staging_params[key] = base_params.get(key, []) + staging_params.get(key, [])

            except AttributeError:

                # The base class does not have the attribute cls._rfm_params
                pass

        # Add the parameters from this class and inherit+filter the
        # parameters from the base classes
        for p in cls.rfm_parameter.parameter_list:
            staging_params[p.name] = p.filt_params(staging_params.get(p.name, [])) + p.values if (
                p.inherit_params) else p.values

        # Make parameter space a class attribute.
        cls._rfm_params = staging_params

        # Define the method to check whether the test is an abstract test.
        def _is_abstract_test(cls):
            for key in cls._rfm_params:
                if (cls._rfm_params[key] == []):
                    return True

            return False

        cls._is_abstract_test = _is_abstract_test


class rfmTest(metaclass=TestMeta):
    '''
    The regression test class.
    '''
    def __init__(self):

        # Abort the class instantiation if the test is an abstract test.
        if self.is_abstract_test():
            raise ValueError('Cannot instantiate an abstract test.') from None

    @classmethod
    def show_parameter_space(cls):
        '''
        Print the parameter space.
        '''
        for key in cls._rfm_params:
            print(key,': ', cls._rfm_params.get(key))

    @classmethod
    def is_abstract_test(cls):
        '''
        Returns True if the test is abstract
        (i.e. w/ parameters declared but not defined).
        '''
        return cls._is_abstract_test(cls)

'''
Basic tests to illustrate how the parameter space works.
'''

class A(rfmTest):
    rfm_parameter('P0', [0, 1, 2, 3])

class B(A):
    rfm_parameter('P1', [2.2])
    rfm_parameter('P0', [-1], inherit_params=True, filt_params = lambda x: x[:-1])

class C(B):
    rfm_parameter('P1', [4])

class D(rfmTest):
    rfm_parameter('P0', [90])

# class E(C,D):
#     pass

class F(C):
    rfm_parameter('P0', []) # Make test an abstract test

class G(F,D):
    pass

if __name__ == '__main__':
    # The base test
    A.show_parameter_space() # {'P0': [0, 1, 2, 3]}

    # Filtering on 'P0' and adding 'P1'
    B.show_parameter_space() # {'P0': [0, 1, 2, -1], 'P1': [2.2]}

    # Redefining 'P1'
    C.show_parameter_space() # {'P0': [0, 1, 2, -1], 'P1': [4]}

    # Another test with 'P0'
    D.show_parameter_space() # {'P0': [90]}

    # Multiple inheritance conflict error on 'P0'
    #E.show_parameter_space() # Doesn't work.

    # We can manually resolve this conflict. If we make C an abstract test by
    # setting 'P0' as undefined ...
    F.show_parameter_space() # {'P0': [], 'P1': [4]}
    # ... the multiple inheritance now works conflict free.
    G.show_parameter_space() # {'P0': [90], 'P1': [4]}

    # However, because F is an abstract test, it will fail if
    # we try to instantiate it
    # f = F() # Cannot instantiate an abstract test error.
```

**Comment by vkarak** [comment] 2020-11-02 17:31
@jjotero et al. here I've created a new project, were we are going to create different issues for all the new ideas discussed here. From now on, let's keep this issue only for what its titles implies, which is essentially about what @jjotero has posted in his comment [above](https://github.com/eth-cscs/reframe/issues/1555#issuecomment-720497659).

**Comment by vkarak** [comment] 2020-11-02 20:58
I will close this issue. I have created individual issues with all the ideas that we came up here. Have a look at #1567, #1568 and #1569. Please feel free to comment in those issues directly.

**Closed by vkarak** 2020-11-02 20:58 UTC
Labels: feature request, prio: normal
