### ISSUE TITLE
Strange behaviour when redefining hook and assigning it to a different stage

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#2397] opened 2022-01-25 21:17 UTC
The following code leads to the strange behaviour that the second `check_x()` overrides the first (as expected) but the hooks are not overridden, leaving the second `check_x()` executing as a post-init hook. We should either disable redefinitions of the same hook in the same class or have the second definition *and* hook override completely the first one.

```python
@simple_test
class my_test(RegressionTest):
    x = variable(int, value=10)

    @run_after('init')
    def check_x(self):
        '''Test will not be listed or run if filtered here'''
        self.skip_if(self.x < 3, 'x is lower than 3')

    @run_after('setup')
    def check_x(self):
        '''Test will be skipped during runtime'''
        self.skip_if(self.x < 5, 'x is lower than 5')
```

**Comment by vkarak** [comment] 2022-02-15 18:03
I don't think so, because if I run:

```
./bin/reframe -c ../misc/rfm-support/issue-2397/test.py -l -S x=1
```

Then the test is skipped due to the post-setup hook, which is not what you would expect, since the "setup" phase has not yet been executed:

```
./bin/reframe: skipping test 'my_test': x is lower than 3
```

The second definition of `check_x` replaces the first one (as expected), but the hook is not updated.

**Comment by teojgo** [comment] 2022-02-16 07:58
> I don't think so, because if I run:
> 
> ```
> ./bin/reframe -c ../misc/rfm-support/issue-2397/test.py -l -S x=1
> ```
> 
> Then the test is skipped due to the post-setup hook, which is not what you would expect, since the "setup" phase has not yet been executed:
> 
> ```
> ./bin/reframe: skipping test 'my_test': x is lower than 3
> ```
> 
> The second definition of `check_x` replaces the first one (as expected), but the hook is not updated so the second `check_x` executes as a post-init hook. I think that we should probably not allow redefinitions of hooks.

Ok, now it's clear, thanks.

**Comment by teojgo** [comment] 2022-02-17 15:23
What actually happens is the following:

1. `check_x` is first added to the hook registry as a `post_init` hook https://github.com/eth-cscs/reframe/blob/12b48588980e411fbfe17f32b864fd6eaf7450b5/reframe/core/hooks.py#L154
2. `check_x` is added to the hook registry as a `post_setup` hook, but because it's wrapped as a `Hook` instance and has the same name as the `check_x` on step 1, it's not taken into account, since a hook with the same name is already in the registry
3. Finally when the hooks are assigned to each stage of the pipeline via https://github.com/eth-cscs/reframe/blob/12b48588980e411fbfe17f32b864fd6eaf7450b5/reframe/core/hooks.py#L82,  the hook that resides in the registry is the `post_init` one with the `check_x` name, but the RegressionTest object attribute named `check_x` refers to the second `check_x` function that replaced the first.
4. Therefore, you have the second `check_x` executed as a `post_init` hook

I suggest overriding completely a hook with the same name if redefined as another stage hook.

**Comment by vkarak** [comment] 2022-02-17 18:09
Nice find and intricate bug! Thanks @teojgo for investigating!

> I suggest overriding completely a hook with the same name if redefined as another stage hook.

Yes, I think it makes sense and it is compatible with what happens when a hook is redefined in a subclass.

**Closed** 2022-02-21 07:53 UTC
Labels: bug, prio: normal, test syntax
