### ISSUE TITLE
Support SGE scheduler

### ISSUE THREAD

**Issue by giordano** [eth-cscs/reframe#1937] opened 2021-04-19 19:19 UTC
It'd be great to support SGE as scheduler.  I'm trying to use PBS as they are somewhat similar, but polling doesn't seem to really work: at
https://github.com/eth-cscs/reframe/blob/45fbacb23210c757724882a13c4a53f33af04800/reframe/core/schedulers/pbs.py#L186
the command `qstat -f Your` is executed for me, I guess there is something wrong going on.

I might be able to work on this implementation in the near future, it shouldn't be too different from PBS, but I'll likely need some assistance along the way :slightly_smiling_face:

**Comment by vkarak** [comment] 2021-04-19 20:40
Hi @giordano, it seems -from what I've read- that for SGE the right command would be `qstat -f -j [job_list]`. But again I've no idea if the output is the same, so some adaptations to the parsing may be needed as well. Can you try hacking the PBS backend and see if you can make it work for SGE. It will be very helpful to understand what are the differences between the two, so then we can adapt the backends and simply create an extension for the SGE scheduler.

**Comment by giordano** [comment] 2021-04-19 21:04
> Can you try hacking the PBS backend and see if you can make it work for SGE.

Yes, that's what I'd like to do, but I'm a bit lost at the moment about where the job list should be coming from.  I got to
https://github.com/eth-cscs/reframe/blob/45fbacb23210c757724882a13c4a53f33af04800/reframe/frontend/executors/policies.py#L443-L445
but then I don't know where/how `_running_tasks[partname]` is set.  Sorry, I'm not (yet) familiar with reframe codebase :slightly_smiling_face:

**Comment by vkarak** [comment] 2021-04-19 21:34
Actually, there is no need to look outside the scheduler backends. To implement a scheduler backend you only need to implement the interface of the `JobScheduler` abstract class. As soon as you do this, and you decorate your scheduler class with `@register_scheduler(name)` it should be integrated with the framework and ready to be used. Job schedulers manage `Job` instances, which are the job descriptors and contain the information about the job has been submitted. The rest of the framework does not know about the backends at all. The framework will call `Job.create()` to create a new job with all the information retrieved by the test spec. This in turn will call the `make_job()` method of the scheduler backend. `Job` is not abstract, but backends may choose to extend it just to add additional fields relevant for them, see for example the `_PbsJob`. The rest of the `JobScheduler` API takes either a single job or a list of jobs to process. If you look into the `reframe.core.schedulers` module you will see the documentation for each API function. Practically, for a scheduler backend, the most important methods are the `emit_preamble(job)`, the `submit(job)`, the `cancel(job)` and the `poll(*jobs)`. The `poll` method may take multiple jobs at once, because it is more efficient to issue a single poll command and retrieve the state of multiple jobs instead of polling each one individually. How is this going to be implemented is entirely up to the backend.

And a small correction to the documentation of the API. The following is not correct:

https://github.com/eth-cscs/reframe/blob/45fbacb23210c757724882a13c4a53f33af04800/reframe/core/schedulers/__init__.py#L86-L95

The `finished()` method does not poll (this is a stale comment 😬 ). The `poll()` method polls and `finished()` simply retrieves the job state (whether a job has finished or not) and raises any job-related error that has happened during polling.

The `filternodes()` and `allnodes()` methods are not essential (see PBS backend) unless you want your backend to support flexible jobs (see [here](https://reframe-hpc.readthedocs.io/en/stable/tutorial_advanced.html#flexible-regression-tests)).

**Comment by vkarak** [comment] 2021-04-21 11:33
Hi @giordano, looking again into your original message about the `qstat -f Your` being executed, it seems that the job submission must be adapted for the SGE scheduler. When ReFrame submits a job with `qsub` looks in the output of the command for the Job ID that was assigned to the job. This is the regex used to retrieve the job id for the PBS scheduler:

https://github.com/eth-cscs/reframe/blob/247c7f070e30af7868af075a7676b2a7d81a49d3/reframe/core/schedulers/pbs.py#L142

**Comment by giordano** [comment] 2021-04-21 15:19
That was helpful, thanks!  When submitting a job with SGE I get
```
Your job <job id> ("<filename>") has been submitted
```
I'm now going through the other changes of the syntax.

**Closed** 2021-07-26 20:43 UTC
Labels: feature request, prio: normal
