### ISSUE TITLE
How to reuse previous compilations?

### ISSUE THREAD

**Issue by sjpb** [eth-cscs/reframe#1313] opened 2020-05-12 14:24 UTC
As far as I can see, test dependencies only allow you to reuse compilations for multiple tests *within* a single run of reframe, not between runs, is that right? I can see why, but is there an easy way to reuse a binary built in a previous run? (assuming I have some way to know its actually the correct binary, which is not trivial.)

What I've come up with so far is:

1. Define a build system which doesn't do anything:
```python
class NoBuild(BuildSystem):
    def __init__(self):
        super().__init__()
    def emit_build_commands(self, environ):
        return []
```
2. Create  a  `CompileOnlyRegressionTest` with a `run_before('compile')`-tagged method which
- checks for a binary in a `builds` tree.
- if it exists, copy it to the `stage` directory then set the `build_system` to `NoBuild()`

Just wondering if there's an easier way!

**Comment by vkarak** [comment] 2020-05-12 20:41
Hi @sjpb, indeed dependencies are not valid across ReFrame runs. Regarding your scenario, if I  understood correctly, you need something like a build cache for previous runs, right? So that when you rerun the same test, you don't to have to rebuild it. I don't see an easier way to do that, except that you could avoid the manual copy to the stage directory by setting the `sourcesdir` to point to your build cache if the binary exists. If you want to avoid the `NoBuild` build system, you could also write a base `CachedRegressionTest` that would behave as a normal `RegressionTest` if there is no hit in the cache or as a `RunOnlyRegressionTest` otherwise. This is easy, too, but currently not so future proof, because you will have to rely on some internal APIs. It would be easier if the "copy-to-stage" was a separate pipeline stage, which we may introdue in the future.

**Comment by sjpb** [comment] 2020-05-13 09:54
Thanks, yes you understand me right - basically because compiling something like gromacs repeatedly is pretty painful.

As you suggested setting `sourcesdir` when using the cached binary is definitely a better approach - it avoids reframe wiping out the copied binary if `sourcesdir` needs to be set for the actual compile.

How could the suggested `CachedRegressionTest` switch behaviors? Presumably it would need to derive from one or the other?

It would also be a lot easier to debug both this type of code and issues with the compile not producing what reframe expects if there was a way to stop reframe deleting & recreating the state dir - then at least the actual "compile" would be really quick. But I guess that's a separate feature request.

**Comment by vkarak** [comment] 2020-05-13 11:12
Here is possible implementation for this `CachedRegressionTest` (I haven't tested it):

```python
class CachedRegressionTest(rfm.RegressionTest, special=True):
    def compile(self):
        if not build_in_cache():
            super().compile(self)
        else:
            self.sourcesdir = fetch_builddir_from_cache()
            return

    def compile_wait(self):
        if not build_in_cache():
            super().compile_wait(self)
        else:
            return

    def run(self):
        if build_in_cache():
            self._copy_to_stagedir(os.path.join(self._prefix,
                                                self.sourcesdir))

        super().run(self)
```

> It would also be a lot easier to debug both this type of code and issues with the compile not producing what reframe expects if there was a way to stop reframe deleting & recreating the state dir - then at least the actual "compile" would be really quick. But I guess that's a separate feature request.

Actually, there is this possibility internally, but not exposed. I think that's a valid feature request and we could implement it easily now that the new configuration mechanism is in place. What we usually do for debugging such issues is to switch to the stage directory of the failing test and manually change the build script generated by ReFrame, then port back these changes to ReFrame.

Have you considered using EasyBuild or Spack from ReFrame to compile GROMACS? I know that @victorusu has experimented quite extensively with that.

**Comment by victorusu** [comment] 2020-05-14 11:03
@sjpb, I have played a bit with this sometime ago.
I have shared [this gist](https://gist.github.com/victorusu/6354944faef2e99653a21d5ae6d116a6) to show you more or less the concept.

The class that runs GROMACS is not shown. But it can be easily created from the [GROMACS test](https://github.com/eth-cscs/reframe/blob/master/cscs-checks/apps/gromacs/gromacs_check.py)

**Comment by vkarak** [comment] 2020-06-08 12:49
@sjpb I have created a feature request about reusing the stage directory here: https://github.com/eth-cscs/reframe/issues/1366

**Comment by vkarak** [comment] 2020-06-09 18:44
@sjpb Can I close this now? Providing in the framework the functionality of a build cache for previous tests is a bit debatable. I think it will get into problems that are much better solved by other tools. I think though that #1366 is a valid request and could mitigate the problem discussed here during debugging.

**Comment by sjpb** [comment] 2020-06-10 10:47
Yes feel free to close, thank you for your help. I think actually my use-case is a bit unusual as I'm using it to test the system, not the code, hence features like this are maybe less relevant to reframe's goal.

If you had the appetite though I'd actually be really interested in a discussion about what we're doing with ReFrame at some point.

**Comment by vkarak** [comment] 2020-06-10 10:49
> If you had the appetite though I'd actually be really interested in a discussion about what we're doing with ReFrame at some point.

Yes, sure, that'd be interesting! You can join our Slack channel and we can schedule a chat there.

**Closed by vkarak** 2020-06-10 10:49 UTC
Labels: help wanted
