### ISSUE TITLE
Os error when running with async execution policy

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#291] opened 2018-05-25 14:47 UTC
The error is `OS error: [Errno 39] Directory not empty` and it seems to be related to the removal of directories.

**Comment by vkarak** [comment] 2018-05-25 14:47
@teojgo Can you please comment how to reproduce and on which system?

**Comment by vkarak** [comment] 2018-05-25 15:16
It fails consistently also for me on Dom:

```
./reframe.py -C config/cscs.py -c cscs-checks/libraries/magma/magma_checks.py --exec-policy=async -r
```

**Comment by teojgo** [comment] 2018-06-20 08:05
As already discussed, @vkarak you can close this issue since we cannot reproduce and we have not observed it happening again.

**Comment by vkarak** [comment] 2018-06-20 13:57
I can't reproduce it either. Seems like a transient system issue. Closing it.

**Comment by vkarak** [comment] 2018-07-25 11:54
I am reopening this, cos this is still happening from time to time.

**Comment by teojgo** [comment] 2018-08-21 07:50
This issue seems to be related to the network file system. They had the same problem in Easybuild, https://github.com/easybuilders/easybuild-framework/pull/353.

**Comment by vkarak** [comment] 2018-08-28 15:05
Perhaps we can replace `rmtree` with our more persistent version as Easybuild does.

**Closed** 2018-09-04 08:44 UTC
Labels: bug, prio: normal
