### ISSUE TITLE
performance report does not accept str

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/reframe#1146] opened 2020-01-30 17:21 UTC
Running this check [src](https://gist.github.com/jgphpc/11fc212945ef1beb7e44c2998afe1e25)
works:

```
PERFORMANCE REPORT
------------------------------------------------------------------------------
ExampleRunOnlyTest
- dom:login
   - PrgEnv-cray
      * num_tasks: 1
      * elapsed_time: 8 s
      * filename: 9.c <---------- yes
```

but fails with:

```
FAILURE INFO for ExampleRunOnlyTest
  * System partition: dom:login
  * Environment: PrgEnv-cray
  * Stage directory: /apps/common/UES/sandbox/jgp/hpctools.git/reframechecks/common/sphexa/DEBUGJG/JIRA1/stage/dom/login/PrgEnv-cray/ExampleRunOnlyTest
  * Node list: dom101
  * Job type: local (id=4458)
  * Maintainers: ['x']
  * Failing phase: performance
  * Reason: unexpected error: '>=' not supported between instances of 'str' and 'float'
Traceback (most recent call last):
  File "/apps/common/UES/sandbox/jgp/reframe.git.jgphpc/reframe/frontend/executors/__init__.py", line 163, in _safe_call
    return fn(*args, **kwargs)
  File "/apps/common/UES/sandbox/jgp/reframe.git.jgphpc/reframe/core/pipeline.py", line 96, in _fn
    func(obj, *args, **kwargs)
  File "/apps/common/UES/sandbox/jgp/reframe.git.jgphpc/reframe/core/pipeline.py", line 1235, in performance
    self.check_performance()
  File "/apps/common/UES/sandbox/jgp/reframe.git.jgphpc/reframe/core/pipeline.py", line 1319, in check_performance
    'expected {1} (l={2}, u={3})' % tag))
  File "/apps/common/UES/sandbox/jgp/reframe.git.jgphpc/reframe/utility/sanity.py", line 727, in evaluate
    return expr.evaluate()
  File "/apps/common/UES/sandbox/jgp/reframe.git.jgphpc/reframe/core/deferrable.py", line 53, in evaluate
    ret = self._fn(*fn_args, **fn_kwargs)
  File "/apps/common/UES/sandbox/jgp/reframe.git.jgphpc/reframe/utility/sanity.py", line 546, in assert_reference
    evaluate(assert_bounded(val, lower, upper))
  File "/apps/common/UES/sandbox/jgp/reframe.git.jgphpc/reframe/utility/sanity.py", line 727, in evaluate
    return expr.evaluate()
  File "/apps/common/UES/sandbox/jgp/reframe.git.jgphpc/reframe/core/deferrable.py", line 53, in evaluate
    ret = self._fn(*fn_args, **fn_kwargs)
  File "/apps/common/UES/sandbox/jgp/reframe.git.jgphpc/reframe/utility/sanity.py", line 492, in assert_bounded
    if val >= lower and val <= upper:
TypeError: '>=' not supported between instances of 'str' and 'float'
```

Would be nice to have reframe support this. 
Would be super nice to have this (being able to use a string for the unit) supported:

```
      * elapsed_time: 8 (9.c)
````

**Comment by vkarak** [comment] 2020-01-30 18:32
Good catch @jgphpc. The fact that it fails badly is definitely a bug. Now, whether we need to support non-numbers in the sanity function that asserts the reference is a different thing.

**Comment by jgphpc** [comment] 2020-01-31 10:31
I am ok with waiting for non number units. For the sake of discussion, here is how i would see it as a user:

```
    @property
    @sn.sanity_function
    def fnm(self):
        result = ['0', '(0.c)']
        return result
```

and 

```
        self.perf_patterns = {
            'filename': self.fnm[0],
        }
        self.reference = {
            '*': {
                'filename': (0, None, None, self.fnm[1]),
            }
        }
```

**Comment by vkarak** [comment] 2020-01-31 10:42
The problem is not due to the units. Units can be strings and, in fact, they are almost always strings. The problem in your case is that you have listed `filename` as performance variable [here](https://gist.github.com/jgphpc/11fc212945ef1beb7e44c2998afe1e25#file-reframe_str_in_sanity-py-L21). The value of that variable is returned as a string by your sanity function [here](https://gist.github.com/jgphpc/11fc212945ef1beb7e44c2998afe1e25#file-reframe_str_in_sanity-py-L40). When ReFrame evaluates the performance, it checks whether its value (i.e., the result of `fnm`) is within the bounds from the reference value by using numeric comparisons apparently. That's why you get the error. And that's why I don't understand why you need to list `filename` as performance variable.

**Comment by jgphpc** [comment] 2020-01-31 10:52
You're right, actually this works without error:

```python
        self.perf_patterns = {
            'elapsed_time': self.elapsed,
            'filename': self.file_line,
        }
        self.reference = {
            '*': {
                'elapsed_time': (0, None, None, 's'),
                'filename': (0, None, None, self.file_name),
            }
```

**Comment by vkarak** [comment] 2020-01-31 11:09
@jgphpc Do not close it, the fact that you got this "crash" is a bug, even if you used it wrongly. It should have given a more user friendly error!

**Closed** 2020-02-24 15:01 UTC
Labels: bug, prio: normal
