### ISSUE TITLE
'just in time' logging?

### ISSUE THREAD

**Issue by bcfriesen** [eth-cscs/reframe#1047] opened 2019-11-12 21:24 UTC
NERSC sends data from ReFrame performance tests to a syslog port. ReFrame is configured at NERSC to run a series of benchmarks each night. A small number of the benchmarks have been failing due to my own errors, but I noticed that the result of having even a single test fail is that ReFrame does not send any of the performance data to syslog, even for the tests which passed. 

Is it possible to 'flush' the log data as each test completes (whether passing or failing) so that the data from successful tests is not lost to history due to other unrelated tests failing?

**Comment by vkarak** [comment] 2019-11-13 08:41
Hi @bcfriesen, this sounds a bit strange. I guess you didn't cancel the run. Which execution policy were you using?

**Comment by bcfriesen** [comment] 2019-11-13 14:39
Hi @vkarak, I observed this behavior both with and without the `async` policy.

**Comment by vkarak** [comment] 2019-11-13 14:41
How did it fail? Did you get the final summary report or did it crash badly? I am trying to investigate the path it took. If you have a reproducer, it'd be great. Meanwhile I'll try to look into it in more detail.

**Comment by bcfriesen** [comment] 2019-11-13 14:43
It seems to fail 'correctly' - at the end it shows the summary of tests that passed and failed:

```
...
[  FAILED  ] Ran 16 test case(s) from 11 check(s) (1 failure(s))
[==========] Finished on Wed Nov 13 06:28:50 2019 

==============================================================================
SUMMARY OF FAILURES
------------------------------------------------------------------------------
FAILURE INFO for GTC_small 
...
```

**Comment by vkarak** [comment] 2019-11-13 15:08
I'll check it out.

**Comment by bcfriesen** [comment] 2019-11-13 17:06
I just verified that the log data shows up on syslog as expected if the test campaign completes with all tests passing. (Actually I just ran a single test.)

**Comment by vkarak** [comment] 2019-11-13 22:13
But it doesn't if even a single one fails?

**Comment by bcfriesen** [comment] 2019-11-13 22:21
Correct.

**Comment by vkarak** [comment] 2019-11-13 23:47
I am trying to reproduce this, but I cannot for the moment. Could you share your logging configuration? Also, in which phase did the test fail?

**Comment by vkarak** [comment] 2019-11-21 07:54
@bcfriesen I will close this, since we have found the root cause. It is not due to ReFrame but rather due to the specific setup of logging at NERSC. Addressing #1056 will enable support for your use case.

**Closed by vkarak** 2019-11-21 07:54 UTC
Labels: help wanted, prio: normal
