### ISSUE TITLE
custom site configuration file cannot be named settings.py

### ISSUE THREAD

**Issue by smoors** [eth-cscs/reframe#1375] opened 2020-06-16 09:20 UTC
if you specify your own site configuration file with for example
```
reframe -C config/settings.py ...
```
ReFrame will ignore it and use the generic `settings.py` provided with the installation instead.

**Comment by vkarak** [comment] 2020-07-07 11:28
Hi @smoors, I'm trying to reproduce this, but I can't:

```bash
cp config/tresa.py config/settings.py
./bin/reframe -C config/settings.py --show-config=systems
```

```javascript
[
  {
    "name": "tresa",
    "hostnames": [
      ".*"
    ],
    "partitions": [
      {
        "name": "default",
        "scheduler": "local",
        "launcher": "local",
        "environs": [
          "builtin"
        ],
        "container_platforms": [
          {
            "type": "Docker"
          }
        ],
        "max_jobs": 8
      }
    ]
  }
]
```

Which is obviously my laptop's configuration and not the generic one.

**Comment by vkarak** [comment] 2020-09-25 19:48
Hi @smoors is this still an issue? I could not reproduce it.

**Comment by vkarak** [comment] 2020-11-07 16:42
I'm closing this. Feel free to reopen it, if the issue is still there.

**Closed by vkarak** 2020-11-07 16:42 UTC
Labels: help wanted, prio: normal
