### ISSUE TITLE
pipy installation does not show performance report 

### ISSUE THREAD

**Issue by computingdolas** [eth-cscs/reframe#905] opened 2019-08-21 13:11 UTC
When I try to use pip install reframe-hpc and try to use the --performance-report, I don't see any  performance report values and there are some errors.

See below example.

PERFORMANCE REPORT
------------------------------------------------------------------------------
HPCGCheck
- cartesius:normal-haswell
   - eb-foss
      * gflops: gflops 0.1
------------------------------------------------------------------------------

**Comment by teojgo** [comment] 2019-08-21 13:46
@computingdolas thanks for reporting the issue. It seems to be the same as #816. It was solved in #818 and therefore the fix will be included in version 2.19. Currently version 2.18 is the latest stable. If you want you can always clone the latest dev version directly from the repo.

**Comment by computingdolas** [comment] 2019-08-21 14:53
Thank you for the info. Yes, currently I am using cloned version.

**Comment by teojgo** [comment] 2019-08-21 14:56
@computingdolas so the latest dev version works fine right?

**Comment by vkarak** [comment] 2019-08-22 16:21
@computingdolas We are going to release 2.19 asap, so the fix will appear on PyPI as well.

I am closing this, since it's a duplicate of #816 as @teojgo pointed out.

**Closed by vkarak** 2019-08-22 16:21 UTC
Labels: bug, duplicate

**Comment by computingdolas** [comment] 2019-08-23 07:13
Yes for sure.
