### ISSUE TITLE
Version mismatch when bootstrapping with pygelf

### ISSUE THREAD

**Issue by jlinford** [eth-cscs/reframe#2138] opened 2021-08-18 18:29 UTC
Hi,

As in title:

```
[johlin02@pacu01 reframe]$ ./bootstrap.sh +pygelf
==> python3 -m ensurepip --root /home/johlin02/x/reframe/external/ --default-pip
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages
Requirement already satisfied: pip in /usr/lib/python3.6/site-packages
==> python3 -m pip install --no-cache-dir -q --upgrade pip --target=external/
==> [+pygelf] python3 -m pip install --no-cache-dir -q -r /tmp/tmp.o14WvcCuHZ --target=external/ --upgrade
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
botocore 1.18.15 requires urllib3<1.26,>=1.20, but you have urllib3 1.26.6 which is incompatible.
[johlin02@pacu01 reframe]$ 
```

To fix, just specify the urllib3 version in requirements.txt:

```
urllib3==1.25.11
```

My company's legal requirements prohibit a pull request, so I'm politely asking someone else to make this change.

Thanks!

**Comment by vkarak** [comment] 2021-08-18 19:46
Hi @jlinford, thanks for spotting this! We'll fix it for the upcoming release.

**Comment by teojgo** [comment] 2021-08-19 09:51
@jlinford it seems that the problem is specific to your setup and the version of the botocore that you have installed. You can instruct the bootstrap script to run pip without trying to upgrade the dependencies:

`./bootstrap.sh --pip-opts="--no-deps" +pygelf`

Let me know if it works for you.

**Comment by vkarak** [comment] 2021-08-25 08:49
@jlinford I will close this issue now. Feel free reopen it.

**Closed by vkarak** 2021-08-25 08:49 UTC
Labels: help wanted, packaging
