### ISSUE TITLE
Send node name in syslog

### ISSUE THREAD

**Issue by difey** [eth-cscs/reframe#1437] opened 2020-07-27 06:09 UTC
Hi, there

We use our log in node to run frame and a database node outside out cluster to collect performance logs. We`d like to know the compute node name even if the perf checks passed to support more works. 

But in my mind,  the only message can be passed is listed in [common-logging-handler-properties](https://reframe-hpc.readthedocs.io/en/latest/config_reference.html#logging-.handlers_perflog-.format).

So, is there any way to get that?

Thanks

**Comment by difey** [comment] 2020-07-27 06:12
> Hi, there
> 
> We use our log in node to run frame and a database node outside out cluster to collect performance logs. We`d like to know the compute node name even if the perf checks passed to support more works.
> 
> But in my mind, the only message can be passed is listed in [common-logging-handler-properties](https://reframe-hpc.readthedocs.io/en/latest/config_reference.html#logging-.handlers_perflog-.format).
> 
> So, is there any way to get that?
> 
> Thanks

**Comment by vkarak** [comment] 2020-07-28 04:10
Hi @difey, currently you can’t select the node list for a test as a formatting field. This is easy to support. I will change that to a feature request.

**Comment by vkarak** [comment] 2020-07-28 04:12
Hmm, this is a duplicate of #1068, so I will close it. Feel free to comment that issue as well.

**Closed by vkarak** 2020-07-28 04:12 UTC
Labels: feature request, prio: normal
