### ISSUE TITLE
Update official EB recipe to use the `./bootstrap.sh` script

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1615] opened 2020-11-23 14:07 UTC

**Comment by teojgo** [comment] 2020-11-26 14:37
@vkarak I am not sure that the bootstrap script can be used in the official EB recipe. In order to pass the EasyBuild ci, the package itself should not download any dependency with pip.

**Comment by vkarak** [comment] 2020-11-26 14:41
We talked already with @boegel about this. ReFrame's installation does not mess at all with the system python or any other Python installation in the system. It just uses pip to download its dependencies under `external/` and then ReFrame sets its own `sys.path` internally. Also all versions of the dependencies are pinned.

**Comment by teojgo** [comment] 2020-11-26 14:43
Ok, I will do it then.

**Comment by boegel** [comment] 2020-11-26 15:28
One potential issue here: you can't assume that `pip` (or `pip3`) is always there.

But in an easyconfig we can just installed `pip` + `ReFrame` in a bundle to make sure `pip` is there (and that we control the version being used for the installation).

**Comment by boegel** [comment] 2020-11-26 15:30
We usually don't like that stuff gets auto-downloaded, but in this case it's sort of OK as long as the versions are pinned in `requirements.txt`. We mainly want to ensure the installation is reproducible, not that `pip` automatically downloads whatever latest version of dependencies (that may work today, it may not tomorrow).

Ideally, the bootstrap should also pulls down the installation files that are required (in case they disappear from PyPI...)

**Comment by vkarak** [comment] 2020-11-26 15:35
> One potential issue here: you can't assume that pip (or pip3) is always there.

Indeed, this is true. I thin in Ubuntu and Debian you have to download pip separately.

> We mainly want to ensure the installation is reproducible, not that pip automatically downloads whatever latest version of dependencies (that may work today, it may not tomorrow).

I agree with that, that's why we pinned everything.

The whole point with this script is that I wanted it to be easily installable and easy to use outside any build system. It's the equivalent I guess to what you are doing when install EB and similar to what Spack does, that it has all of its dependencies in the repo. I could do that as well, but I wanted to avoid bloating the repo and having to maintain the `external/` directory up to date.

> Ideally, the bootstrap should also pulls down the installation files that are required (in case they disappear from PyPI...)

This I don't understand it very well tbh. Aren't the pinned requirements enough?

**Comment by teojgo** [comment] 2020-11-26 15:36
@boegel so in this case is it better to go for a `PythonPackage` or stay in a `PythonBundle`?

**Comment by vkarak** [comment] 2020-11-26 15:39
For me the important thing is not to install any Python. I want to go with the system Python. Can't we view it as a system tool?

**Comment by boegel** [comment] 2020-11-26 15:45
> > Ideally, the bootstrap should also pulls down the installation files that are required (in case they disappear from PyPI...)
> 
> This I don't understand it very well tbh. Aren't the pinned requirements enough?

In theory, yes, as long as PyPI serves the files required to install those versions.
If it doesn't (either permanently, or temporarily), or if the system you're on can't talk to PyPI (offline, airgapped network, AWS down, etc.) you're lost, and you can't reproduce the installation...

That won't happen in EasyBuild, since it downloads all the source files. Once you've done an installation (and you haven't trashed your source archive), you can reproduce the installation offline.

> @boegel so in this case is it better to go for a `PythonPackage` or stay in a `PythonBundle`?

If you need to install both `pip` and ReFrame, you'll still need to use bundle.

> For me the important thing is not to install any Python. I want to go with the system Python. Can't we view it as a system tool?

Sure, that's what we also do now in the latest `ReFrame` easyconfig (see https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/ReFrame/ReFrame-3.2.eb); we use the system Python, but make sure it's recent enough (Python 3.6 or newer), so EasyBuild will check whether the `python` command meets that, and if not it'll go look for `python3` or `python3.6` on the system, it won't try to install Python to resolve that dep (see `allow_system_deps`)

**Comment by teojgo** [comment] 2021-01-18 11:43
This was fixed by merging of https://github.com/easybuilders/easybuild-easyconfigs/pull/11787

**Closed by teojgo** 2021-01-18 11:43 UTC
Labels: packaging, prio: normal
